services:
  mongodb:
    image: mongodb/mongodb-community-server
    env_file:
      - ./DeliveryApp-frontend/mongodb.env
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./database_mongo
        target: /data/db
